version: '3'
services:
    web:
        image: nginx:1.21.6-alpine
        container_name: '${COMPOSE_PROJECT_NAME}-web'
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./app:/app
        depends_on:
            - php
            - phpmyadmin
    php:
        build:
            context: .
            dockerfile: ./docker/php/PHP.Dockerfile
        container_name: '${COMPOSE_PROJECT_NAME}-php' 
        volumes:
            - ./app:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
          - db
    db:
        image: yobasystems/alpine-mariadb:10.6.4
        container_name: '${COMPOSE_PROJECT_NAME}-db'
        restart: 'always'
        ports:
          - "127.0.0.1:3306:3306"
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        
        
    phpmyadmin:
        image: mhzawadi/phpmyadmin:latest
        container_name: '${COMPOSE_PROJECT_NAME}-pma'
        links:
          - db
        environment:
          PMA_HOST: db
          PMA_PORT: 3306
          PMA_USER: root
          PMA_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          
        ports:
          - '8080:80'